### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by ed-mejia** [SwiftValidatorCommunity/SwiftValidator#132]
Hi guys, any plan to upgrade the library to support 3.X ?

**Comment by SebastianBoldt** [comment]
+1

**Comment by ed-mejia** [comment]
I Did the migration to Swift 3 Xcode beta 4, [here](https://github.com/ed-mejia/SwiftValidator/tree/swift3)

If you guys create a swift 3  branch I could pull request to merge it

**Comment by davepatterson** [comment]
@ed-mejia I created a swift-3 branch so you're all set to PR. :100:

**Comment by qgliu** [comment]
any timeline to merge the swift 3 support to master?

**Comment by ossmalpha** [comment]
@qgliu I don't know when it is going to be pushed, but I can let you know that code on swift3-dave branch is working with Swift 3 on Xcode 8 - I just tested it in a new project.

Use this in your Podfile:

`pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'swift3-dave'`

**Comment by ossmalpha** [comment]
Got the following error while I was trying to install pods using iOS version that is older than 10.0. Can it be modified that it can run on older operating systems as well?

**Comment by dhamukrish** [comment]
Even `swift3-dave` is not working now. Please advise as I am getting below error.

```
[!] Unable to satisfy the following requirements:

- `SwiftValidator (from `https://github.com/jpotts18/SwiftValidator.git`, branch `swift3-dave`)` required by `Podfile`

Specs satisfying the `SwiftValidator (from `https://github.com/jpotts18/SwiftValidator.git`, branch `swift3-dave`)` dependency were found, but they required a higher minimum deployment target.

```

**Comment by Lweek** [comment]
Hi! I have written it to all Swift 3 pull requests but I gonna repeat it even here. If you change public to open for all Rule classes and its methods, it will let us modify functionality for app specific purposes. I believe that it is expected behavior and thus required before merge. Thank you! :)

**Comment by racer1988** [comment]
Can we merge the PR about Swift 3...
it is getting a bit late now

**Comment by leizard** [comment]
+1 please I need it too..

**Comment by dhamukrish** [comment]
I have now moved other framework (https://github.com/adamwaite/Validator) due to this dependancy issue.

**Comment by n8stowell82** [comment]
@dhamukrish how long did it take to convert over? Thinking about doing the same.  can't afford to wait much longer

**Comment by dhamukrish** [comment]
@n8stowell82 I have taken 2-3 hours including understanding of framework for first Form

**Comment by ed-mejia** [comment]
Seems like Swift3 branch will never make into master not even merged at all.

Most of the trending open source libs out there have updated master to Swift3 and this _(which is a trending one too imho)_ is still struggling ...

I really don't like the idea to move to a different project, is there anything we can do to actually make this happen?, the project seems hard to move forward.

**Comment by davepatterson** [comment]
@ed-mejia I fixed the travis issue we had with xcode8 so a swift 3 master is right around the corner. The travis problem is the only thing that was holding us back.

**Comment by leizard** [comment]
I tried the swift 3 branch and it works perfectly. My app has the form validation again. Thank you for all your work.

**Comment by PranKe01** [comment]
What about making the version 4.0.1 the master? I tried to install using pod 'SwiftValidator', '~> 4.0.1' but that didn't worked :( I had to use the :git and :tag informations...

**Comment by piv199** [comment]
pod 'Validator' works like a charm, could be closed?
