### ISSUE TITLE
Swift 2.3 Support

### ISSUE THREAD

**Issue by cihadhoruzoglu** [SwiftValidatorCommunity/SwiftValidator#147]
Is there any plan for support Swift 2.3?

**Comment by gbejarano01** [comment]
I just submitted a PR #151, for addressing this, but I see there are 12 PR pending approval... not sure if this is going to be picked up.

**Comment by davepatterson** [comment]
You can merge on the swift-2.3 branch to fulfill this. I noticed in your previous PR that Travis fails. This is likely because you are using an old version of cocoapods by default. This should be fixed by adding the following to travis.yml `before_install:
  - gem install cocoapods -v '0.32.1'`

**Comment by gbejarano01** [comment]
Thanks @davepatterson Unfortunately it looks like I can't merge as I have no permissions, also, now the PR has conflicts because it looks like someone pushed some changes on `master`.

How do you like to proceed'
