### ISSUE TITLE
Is SwiftValidator compatible to Swift 3 ?

### ISSUE THREAD

**Issue by bilawal-liaqat** [SwiftValidatorCommunity/SwiftValidator#159]
Pod updated to Swift3
pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'swift3'

but still getting many errors 

before it I used "swift3-dave" with lot of errors

**Comment by davepatterson** [comment]
Have you tried the swift-3 branch?

**Comment by bilawal-liaqat** [comment]
swift-3 branch working .
 Can you please remove other branches for swift 3 so developer dont get confused.

**Comment by leizard** [comment]
I tried swift 3 branch and it works perfectly. Thank you for migrating!

**Comment by rupalchawla** [comment]
Its not working for me, can anyone help. I used both of them below as mentioned in document but still many errors

pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '3.0.5'
pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.0.0'

**Comment by rupalchawla** [comment]
Nevermind, i was looking in the document of branch swift-3, instead i had to look under master. This one worked 
pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'

**Comment by finddoc** [comment]
BTW, I have tried to use 
pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
However, it seems I can't import SwiftValidator since it can't find this file.

**Comment by davepatterson** [comment]
I don't understand @finddoc. @rupalchawla did the same as you and it worked.
