### ISSUE TITLE
cannot inherit from non-open class Validator outside of its defining module

### ISSUE THREAD

**Issue by cikpis** [SwiftValidatorCommunity/SwiftValidator#167]
Hey guys, 

would be nice to have the inherit even in Validator class. I need to extend some functionality. I believe that changing "public" to "open" is the magic.

Carmelo

**Comment by apprisingapps** [comment]
I am having this issue in subclassing RegexRule as in the documentation example for a project in Swift 3.  Carmelo indicates what the Swift 3 docs purpose as a solution.

**Comment by smamczak** [comment]
Please make Validator class "open" for swift 3

**Comment by Rouix** [comment]
@smamczak Could you explain how to do this? I can not fix the code in someone else's library ...

**Comment by cikpis** [comment]
@Rouix just download the library and ass public from there. This library is not worth to have it due to is not maintained.
