### ISSUE TITLE
class RegexRule still not merged

### ISSUE THREAD

**Issue by kiwo12345** [SwiftValidatorCommunity/SwiftValidator#178]
I just installed `pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'` which will install v4.0.0

But I still get the error: **cannot inherit from non-open class RegexRule outside of its defining module**

Was this never merged into master from https://github.com/jpotts18/SwiftValidator/issues/162 or https://github.com/jpotts18/SwiftValidator/pull/158 ?

**Comment by scottymac** [comment]
+1

**Comment by Yetispapa** [comment]
+1

**Comment by snowywolfie** [comment]
+1

**Comment by davepatterson** [comment]
This got merged in #175
