### ISSUE TITLE
Unable to create custom password rule

### ISSUE THREAD

**Issue by snowywolfie** [SwiftValidatorCommunity/SwiftValidator#183]
I tried to create a custom password rule that inherit regex rule. But it show 
"Cannot inherit from non-open class 'RegexRule' outside of its defining module". Any solution for this?

**Comment by Sadmansamee** [comment]
Find "RegexRule" and change "public class RegexRule : Rule" to "open class RegexRule : Rule"

**Comment by rajatjain4061** [comment]
@snowywolfie RegexRule is now an open class. Your can update your library.
