### ISSUE TITLE
Interested in becoming a contributor

### ISSUE THREAD

**Issue by jpotts18** [SwiftValidatorCommunity/SwiftValidator#204]

**Comment by RajatJain4061** [comment]
@jpotts18 Please give me write permissions so that I can review and merge pull requests.

**Comment by jpotts18** [comment]
@RajatJain4061 Thanks for your help!

**Comment by vdeep** [comment]
@jpotts18 I'm interested in maintaining this repo as I use it in most of my projects. Can you please give me write permissions?
