### ISSUE TITLE
New Validator Design

### ISSUE THREAD

**Issue by jpotts18** [SwiftValidatorCommunity/SwiftValidator#82]
1. Run `validator.validate()`
2. Run a method that might check any preconditions by calling `validationWillRun()` - #34 
3. Validate fields
   - Run Sanitizers - mentioned in #64 
   - Validate each field
4. Call `validator.validationSuccessful()` or `validator.validationFailed()` but make them optional - #44 
5. Run a method that checks any postconditions by calling `validationDidRun()`

**Comment by davepatterson** [comment]
Sounds like a good idea. I will upload a pull request with suggestive implementation of this by tomorrow.
